package com.zlcdgroup.libs.ocr.vo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Readingdata implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_METER_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdMeterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdReading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_READING_REAL
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private BigDecimal rdReadingReal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_UN_READ_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdUnReadType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_RFIDSTATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdRfidstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_WARINGSTATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdWaringstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_PERSON_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdPersonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_PERSON_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdPersonName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_TERMINAL_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdTerminalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_DATASTYLE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdDatastyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_CHECKJOB_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdCheckjobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_JOB_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdJobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_STATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdAuditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdAuditReading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_TIME_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdAuditTimeFirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_UID_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdAuditUidFirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_UNAME_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdAuditUnameFirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_TIME_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdAuditTimeLast;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_UID_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdAuditUidLast;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_UNAME_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdAuditUnameLast;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_IMAGENAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdImagename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_UPTIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdUptime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_PARENT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_RE_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdReReading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_RE_PERSON_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdRePersonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_RE_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdReTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ESTIMATE_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdEstimateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ESTIMATE_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdEstimateReading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ESTIMATE_USER_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdEstimateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ESTIMATE_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdEstimateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_INVALID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdInvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_LOOP
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdLoop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_UPLOAD_UUID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdUploadUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_MEMO
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdMemo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_READING_MIN
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private BigDecimal rdReadingMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_READING_END
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdAuditReadingEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_LOOP_COUNT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdAuditLoopCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_COUNT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdAuditCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_DELAY_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdAuditDelayTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_RE_PERSON_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdRePersonName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ESTIMATE_UNAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdEstimateUname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_AUDIT_UNREAD_END
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdAuditUnreadEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_ESTIMATE_UNREAD
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdEstimateUnread;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_READING_VALID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdReadingValid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_MUST_AUDIT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdMustAudit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_CASE_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdCaseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_CHANGE_METER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdChangeMeter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_CLIENT_NUMBER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdClientNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_USED_WATER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private BigDecimal rdUsedWater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_LASTREADING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdLastreading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_METER_PRECISION
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private BigDecimal rdMeterPrecision;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_VALID_INACCURACY
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Integer rdValidInaccuracy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_JOB_UNIT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdJobUnitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_JOB_UNIT_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdJobUnitName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_BUILDING_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdBuildingId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_BUILDING_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdBuildingName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_GROUP_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_GROUP_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdGroupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_METER_LISTNUMBER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdMeterListnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_METER_LIST_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdMeterListId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_METER_PARENT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private String rdMeterParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_USER_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private Long rdUserReading;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_READINGDATA.RD_USER_USED_WATER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	private BigDecimal rdUserUsedWater;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ID
	 * @return  the value of TB_READINGDATA.RD_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdId() {
		return rdId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ID
	 * @param rdId  the value for TB_READINGDATA.RD_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdId(String rdId) {
		this.rdId = rdId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_METER_ID
	 * @return  the value of TB_READINGDATA.RD_METER_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdMeterId() {
		return rdMeterId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_METER_ID
	 * @param rdMeterId  the value for TB_READINGDATA.RD_METER_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMeterId(String rdMeterId) {
		this.rdMeterId = rdMeterId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_READING
	 * @return  the value of TB_READINGDATA.RD_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdReading() {
		return rdReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_READING
	 * @param rdReading  the value for TB_READINGDATA.RD_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdReading(Long rdReading) {
		this.rdReading = rdReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_READING_REAL
	 * @return  the value of TB_READINGDATA.RD_READING_REAL
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public BigDecimal getRdReadingReal() {
		return rdReadingReal;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_READING_REAL
	 * @param rdReadingReal  the value for TB_READINGDATA.RD_READING_REAL
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdReadingReal(BigDecimal rdReadingReal) {
		this.rdReadingReal = rdReadingReal;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_TIME
	 * @return  the value of TB_READINGDATA.RD_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdTime() {
		return rdTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_TIME
	 * @param rdTime  the value for TB_READINGDATA.RD_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdTime(Long rdTime) {
		this.rdTime = rdTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_UN_READ_TYPE
	 * @return  the value of TB_READINGDATA.RD_UN_READ_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdUnReadType() {
		return rdUnReadType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_UN_READ_TYPE
	 * @param rdUnReadType  the value for TB_READINGDATA.RD_UN_READ_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdUnReadType(Integer rdUnReadType) {
		this.rdUnReadType = rdUnReadType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_RFIDSTATUS
	 * @return  the value of TB_READINGDATA.RD_RFIDSTATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdRfidstatus() {
		return rdRfidstatus;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_RFIDSTATUS
	 * @param rdRfidstatus  the value for TB_READINGDATA.RD_RFIDSTATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdRfidstatus(Integer rdRfidstatus) {
		this.rdRfidstatus = rdRfidstatus;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_WARINGSTATUS
	 * @return  the value of TB_READINGDATA.RD_WARINGSTATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdWaringstatus() {
		return rdWaringstatus;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_WARINGSTATUS
	 * @param rdWaringstatus  the value for TB_READINGDATA.RD_WARINGSTATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdWaringstatus(Integer rdWaringstatus) {
		this.rdWaringstatus = rdWaringstatus;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_PERSON_ID
	 * @return  the value of TB_READINGDATA.RD_PERSON_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdPersonId() {
		return rdPersonId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_PERSON_ID
	 * @param rdPersonId  the value for TB_READINGDATA.RD_PERSON_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdPersonId(String rdPersonId) {
		this.rdPersonId = rdPersonId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_PERSON_NAME
	 * @return  the value of TB_READINGDATA.RD_PERSON_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdPersonName() {
		return rdPersonName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_PERSON_NAME
	 * @param rdPersonName  the value for TB_READINGDATA.RD_PERSON_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdPersonName(String rdPersonName) {
		this.rdPersonName = rdPersonName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_TERMINAL_ID
	 * @return  the value of TB_READINGDATA.RD_TERMINAL_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdTerminalId() {
		return rdTerminalId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_TERMINAL_ID
	 * @param rdTerminalId  the value for TB_READINGDATA.RD_TERMINAL_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdTerminalId(String rdTerminalId) {
		this.rdTerminalId = rdTerminalId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_DATASTYLE
	 * @return  the value of TB_READINGDATA.RD_DATASTYLE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdDatastyle() {
		return rdDatastyle;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_DATASTYLE
	 * @param rdDatastyle  the value for TB_READINGDATA.RD_DATASTYLE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdDatastyle(Integer rdDatastyle) {
		this.rdDatastyle = rdDatastyle;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_CHECKJOB_ID
	 * @return  the value of TB_READINGDATA.RD_CHECKJOB_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdCheckjobId() {
		return rdCheckjobId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_CHECKJOB_ID
	 * @param rdCheckjobId  the value for TB_READINGDATA.RD_CHECKJOB_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdCheckjobId(String rdCheckjobId) {
		this.rdCheckjobId = rdCheckjobId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_JOB_ID
	 * @return  the value of TB_READINGDATA.RD_JOB_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdJobId() {
		return rdJobId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_JOB_ID
	 * @param rdJobId  the value for TB_READINGDATA.RD_JOB_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdJobId(String rdJobId) {
		this.rdJobId = rdJobId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_STATUS
	 * @return  the value of TB_READINGDATA.RD_AUDIT_STATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdAuditStatus() {
		return rdAuditStatus;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_STATUS
	 * @param rdAuditStatus  the value for TB_READINGDATA.RD_AUDIT_STATUS
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditStatus(Integer rdAuditStatus) {
		this.rdAuditStatus = rdAuditStatus;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_READING
	 * @return  the value of TB_READINGDATA.RD_AUDIT_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdAuditReading() {
		return rdAuditReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_READING
	 * @param rdAuditReading  the value for TB_READINGDATA.RD_AUDIT_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditReading(Long rdAuditReading) {
		this.rdAuditReading = rdAuditReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_TIME_FIRST
	 * @return  the value of TB_READINGDATA.RD_AUDIT_TIME_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdAuditTimeFirst() {
		return rdAuditTimeFirst;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_TIME_FIRST
	 * @param rdAuditTimeFirst  the value for TB_READINGDATA.RD_AUDIT_TIME_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditTimeFirst(Long rdAuditTimeFirst) {
		this.rdAuditTimeFirst = rdAuditTimeFirst;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_UID_FIRST
	 * @return  the value of TB_READINGDATA.RD_AUDIT_UID_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdAuditUidFirst() {
		return rdAuditUidFirst;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_UID_FIRST
	 * @param rdAuditUidFirst  the value for TB_READINGDATA.RD_AUDIT_UID_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditUidFirst(String rdAuditUidFirst) {
		this.rdAuditUidFirst = rdAuditUidFirst;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_UNAME_FIRST
	 * @return  the value of TB_READINGDATA.RD_AUDIT_UNAME_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdAuditUnameFirst() {
		return rdAuditUnameFirst;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_UNAME_FIRST
	 * @param rdAuditUnameFirst  the value for TB_READINGDATA.RD_AUDIT_UNAME_FIRST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditUnameFirst(String rdAuditUnameFirst) {
		this.rdAuditUnameFirst = rdAuditUnameFirst;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_TIME_LAST
	 * @return  the value of TB_READINGDATA.RD_AUDIT_TIME_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdAuditTimeLast() {
		return rdAuditTimeLast;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_TIME_LAST
	 * @param rdAuditTimeLast  the value for TB_READINGDATA.RD_AUDIT_TIME_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditTimeLast(Long rdAuditTimeLast) {
		this.rdAuditTimeLast = rdAuditTimeLast;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_UID_LAST
	 * @return  the value of TB_READINGDATA.RD_AUDIT_UID_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdAuditUidLast() {
		return rdAuditUidLast;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_UID_LAST
	 * @param rdAuditUidLast  the value for TB_READINGDATA.RD_AUDIT_UID_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditUidLast(String rdAuditUidLast) {
		this.rdAuditUidLast = rdAuditUidLast;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_UNAME_LAST
	 * @return  the value of TB_READINGDATA.RD_AUDIT_UNAME_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdAuditUnameLast() {
		return rdAuditUnameLast;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_UNAME_LAST
	 * @param rdAuditUnameLast  the value for TB_READINGDATA.RD_AUDIT_UNAME_LAST
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditUnameLast(String rdAuditUnameLast) {
		this.rdAuditUnameLast = rdAuditUnameLast;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_IMAGENAME
	 * @return  the value of TB_READINGDATA.RD_IMAGENAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdImagename() {
		return rdImagename;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_IMAGENAME
	 * @param rdImagename  the value for TB_READINGDATA.RD_IMAGENAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdImagename(String rdImagename) {
		this.rdImagename = rdImagename;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_UPTIME
	 * @return  the value of TB_READINGDATA.RD_UPTIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdUptime() {
		return rdUptime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_UPTIME
	 * @param rdUptime  the value for TB_READINGDATA.RD_UPTIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdUptime(Long rdUptime) {
		this.rdUptime = rdUptime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_PARENT_ID
	 * @return  the value of TB_READINGDATA.RD_PARENT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdParentId() {
		return rdParentId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_PARENT_ID
	 * @param rdParentId  the value for TB_READINGDATA.RD_PARENT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdParentId(String rdParentId) {
		this.rdParentId = rdParentId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_RE_READING
	 * @return  the value of TB_READINGDATA.RD_RE_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdReReading() {
		return rdReReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_RE_READING
	 * @param rdReReading  the value for TB_READINGDATA.RD_RE_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdReReading(Long rdReReading) {
		this.rdReReading = rdReReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_RE_PERSON_ID
	 * @return  the value of TB_READINGDATA.RD_RE_PERSON_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdRePersonId() {
		return rdRePersonId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_RE_PERSON_ID
	 * @param rdRePersonId  the value for TB_READINGDATA.RD_RE_PERSON_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdRePersonId(String rdRePersonId) {
		this.rdRePersonId = rdRePersonId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_RE_TIME
	 * @return  the value of TB_READINGDATA.RD_RE_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdReTime() {
		return rdReTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_RE_TIME
	 * @param rdReTime  the value for TB_READINGDATA.RD_RE_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdReTime(Long rdReTime) {
		this.rdReTime = rdReTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ESTIMATE_TYPE
	 * @return  the value of TB_READINGDATA.RD_ESTIMATE_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdEstimateType() {
		return rdEstimateType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ESTIMATE_TYPE
	 * @param rdEstimateType  the value for TB_READINGDATA.RD_ESTIMATE_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdEstimateType(Integer rdEstimateType) {
		this.rdEstimateType = rdEstimateType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ESTIMATE_READING
	 * @return  the value of TB_READINGDATA.RD_ESTIMATE_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdEstimateReading() {
		return rdEstimateReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ESTIMATE_READING
	 * @param rdEstimateReading  the value for TB_READINGDATA.RD_ESTIMATE_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdEstimateReading(Long rdEstimateReading) {
		this.rdEstimateReading = rdEstimateReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ESTIMATE_USER_ID
	 * @return  the value of TB_READINGDATA.RD_ESTIMATE_USER_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdEstimateUserId() {
		return rdEstimateUserId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ESTIMATE_USER_ID
	 * @param rdEstimateUserId  the value for TB_READINGDATA.RD_ESTIMATE_USER_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdEstimateUserId(String rdEstimateUserId) {
		this.rdEstimateUserId = rdEstimateUserId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ESTIMATE_TIME
	 * @return  the value of TB_READINGDATA.RD_ESTIMATE_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdEstimateTime() {
		return rdEstimateTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ESTIMATE_TIME
	 * @param rdEstimateTime  the value for TB_READINGDATA.RD_ESTIMATE_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdEstimateTime(Long rdEstimateTime) {
		this.rdEstimateTime = rdEstimateTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_INVALID
	 * @return  the value of TB_READINGDATA.RD_INVALID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdInvalid() {
		return rdInvalid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_INVALID
	 * @param rdInvalid  the value for TB_READINGDATA.RD_INVALID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdInvalid(Integer rdInvalid) {
		this.rdInvalid = rdInvalid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_LOOP
	 * @return  the value of TB_READINGDATA.RD_LOOP
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdLoop() {
		return rdLoop;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_LOOP
	 * @param rdLoop  the value for TB_READINGDATA.RD_LOOP
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdLoop(Integer rdLoop) {
		this.rdLoop = rdLoop;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_UPLOAD_UUID
	 * @return  the value of TB_READINGDATA.RD_UPLOAD_UUID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdUploadUuid() {
		return rdUploadUuid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_UPLOAD_UUID
	 * @param rdUploadUuid  the value for TB_READINGDATA.RD_UPLOAD_UUID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdUploadUuid(String rdUploadUuid) {
		this.rdUploadUuid = rdUploadUuid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_MEMO
	 * @return  the value of TB_READINGDATA.RD_MEMO
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdMemo() {
		return rdMemo;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_MEMO
	 * @param rdMemo  the value for TB_READINGDATA.RD_MEMO
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMemo(String rdMemo) {
		this.rdMemo = rdMemo;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_READING_MIN
	 * @return  the value of TB_READINGDATA.RD_READING_MIN
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public BigDecimal getRdReadingMin() {
		return rdReadingMin;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_READING_MIN
	 * @param rdReadingMin  the value for TB_READINGDATA.RD_READING_MIN
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdReadingMin(BigDecimal rdReadingMin) {
		this.rdReadingMin = rdReadingMin;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_READING_END
	 * @return  the value of TB_READINGDATA.RD_AUDIT_READING_END
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdAuditReadingEnd() {
		return rdAuditReadingEnd;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_READING_END
	 * @param rdAuditReadingEnd  the value for TB_READINGDATA.RD_AUDIT_READING_END
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditReadingEnd(Long rdAuditReadingEnd) {
		this.rdAuditReadingEnd = rdAuditReadingEnd;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_LOOP_COUNT
	 * @return  the value of TB_READINGDATA.RD_AUDIT_LOOP_COUNT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdAuditLoopCount() {
		return rdAuditLoopCount;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_LOOP_COUNT
	 * @param rdAuditLoopCount  the value for TB_READINGDATA.RD_AUDIT_LOOP_COUNT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditLoopCount(Integer rdAuditLoopCount) {
		this.rdAuditLoopCount = rdAuditLoopCount;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_COUNT
	 * @return  the value of TB_READINGDATA.RD_AUDIT_COUNT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdAuditCount() {
		return rdAuditCount;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_COUNT
	 * @param rdAuditCount  the value for TB_READINGDATA.RD_AUDIT_COUNT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditCount(Integer rdAuditCount) {
		this.rdAuditCount = rdAuditCount;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_DELAY_TIME
	 * @return  the value of TB_READINGDATA.RD_AUDIT_DELAY_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdAuditDelayTime() {
		return rdAuditDelayTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_DELAY_TIME
	 * @param rdAuditDelayTime  the value for TB_READINGDATA.RD_AUDIT_DELAY_TIME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditDelayTime(Long rdAuditDelayTime) {
		this.rdAuditDelayTime = rdAuditDelayTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_RE_PERSON_NAME
	 * @return  the value of TB_READINGDATA.RD_RE_PERSON_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdRePersonName() {
		return rdRePersonName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_RE_PERSON_NAME
	 * @param rdRePersonName  the value for TB_READINGDATA.RD_RE_PERSON_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdRePersonName(String rdRePersonName) {
		this.rdRePersonName = rdRePersonName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ESTIMATE_UNAME
	 * @return  the value of TB_READINGDATA.RD_ESTIMATE_UNAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdEstimateUname() {
		return rdEstimateUname;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ESTIMATE_UNAME
	 * @param rdEstimateUname  the value for TB_READINGDATA.RD_ESTIMATE_UNAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdEstimateUname(String rdEstimateUname) {
		this.rdEstimateUname = rdEstimateUname;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_AUDIT_UNREAD_END
	 * @return  the value of TB_READINGDATA.RD_AUDIT_UNREAD_END
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdAuditUnreadEnd() {
		return rdAuditUnreadEnd;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_AUDIT_UNREAD_END
	 * @param rdAuditUnreadEnd  the value for TB_READINGDATA.RD_AUDIT_UNREAD_END
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdAuditUnreadEnd(Integer rdAuditUnreadEnd) {
		this.rdAuditUnreadEnd = rdAuditUnreadEnd;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_ESTIMATE_UNREAD
	 * @return  the value of TB_READINGDATA.RD_ESTIMATE_UNREAD
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdEstimateUnread() {
		return rdEstimateUnread;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_ESTIMATE_UNREAD
	 * @param rdEstimateUnread  the value for TB_READINGDATA.RD_ESTIMATE_UNREAD
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdEstimateUnread(Integer rdEstimateUnread) {
		this.rdEstimateUnread = rdEstimateUnread;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_READING_VALID
	 * @return  the value of TB_READINGDATA.RD_READING_VALID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdReadingValid() {
		return rdReadingValid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_READING_VALID
	 * @param rdReadingValid  the value for TB_READINGDATA.RD_READING_VALID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdReadingValid(Integer rdReadingValid) {
		this.rdReadingValid = rdReadingValid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_MUST_AUDIT
	 * @return  the value of TB_READINGDATA.RD_MUST_AUDIT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdMustAudit() {
		return rdMustAudit;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_MUST_AUDIT
	 * @param rdMustAudit  the value for TB_READINGDATA.RD_MUST_AUDIT
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMustAudit(Integer rdMustAudit) {
		this.rdMustAudit = rdMustAudit;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_CASE_TYPE
	 * @return  the value of TB_READINGDATA.RD_CASE_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdCaseType() {
		return rdCaseType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_CASE_TYPE
	 * @param rdCaseType  the value for TB_READINGDATA.RD_CASE_TYPE
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdCaseType(String rdCaseType) {
		this.rdCaseType = rdCaseType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_CHANGE_METER
	 * @return  the value of TB_READINGDATA.RD_CHANGE_METER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdChangeMeter() {
		return rdChangeMeter;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_CHANGE_METER
	 * @param rdChangeMeter  the value for TB_READINGDATA.RD_CHANGE_METER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdChangeMeter(Integer rdChangeMeter) {
		this.rdChangeMeter = rdChangeMeter;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_CLIENT_NUMBER
	 * @return  the value of TB_READINGDATA.RD_CLIENT_NUMBER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdClientNumber() {
		return rdClientNumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_CLIENT_NUMBER
	 * @param rdClientNumber  the value for TB_READINGDATA.RD_CLIENT_NUMBER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdClientNumber(String rdClientNumber) {
		this.rdClientNumber = rdClientNumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_USED_WATER
	 * @return  the value of TB_READINGDATA.RD_USED_WATER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public BigDecimal getRdUsedWater() {
		return rdUsedWater;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_USED_WATER
	 * @param rdUsedWater  the value for TB_READINGDATA.RD_USED_WATER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdUsedWater(BigDecimal rdUsedWater) {
		this.rdUsedWater = rdUsedWater;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_LASTREADING
	 * @return  the value of TB_READINGDATA.RD_LASTREADING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdLastreading() {
		return rdLastreading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_LASTREADING
	 * @param rdLastreading  the value for TB_READINGDATA.RD_LASTREADING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdLastreading(Long rdLastreading) {
		this.rdLastreading = rdLastreading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_METER_PRECISION
	 * @return  the value of TB_READINGDATA.RD_METER_PRECISION
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public BigDecimal getRdMeterPrecision() {
		return rdMeterPrecision;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_METER_PRECISION
	 * @param rdMeterPrecision  the value for TB_READINGDATA.RD_METER_PRECISION
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMeterPrecision(BigDecimal rdMeterPrecision) {
		this.rdMeterPrecision = rdMeterPrecision;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_VALID_INACCURACY
	 * @return  the value of TB_READINGDATA.RD_VALID_INACCURACY
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Integer getRdValidInaccuracy() {
		return rdValidInaccuracy;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_VALID_INACCURACY
	 * @param rdValidInaccuracy  the value for TB_READINGDATA.RD_VALID_INACCURACY
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdValidInaccuracy(Integer rdValidInaccuracy) {
		this.rdValidInaccuracy = rdValidInaccuracy;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_JOB_UNIT_ID
	 * @return  the value of TB_READINGDATA.RD_JOB_UNIT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdJobUnitId() {
		return rdJobUnitId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_JOB_UNIT_ID
	 * @param rdJobUnitId  the value for TB_READINGDATA.RD_JOB_UNIT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdJobUnitId(String rdJobUnitId) {
		this.rdJobUnitId = rdJobUnitId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_JOB_UNIT_NAME
	 * @return  the value of TB_READINGDATA.RD_JOB_UNIT_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdJobUnitName() {
		return rdJobUnitName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_JOB_UNIT_NAME
	 * @param rdJobUnitName  the value for TB_READINGDATA.RD_JOB_UNIT_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdJobUnitName(String rdJobUnitName) {
		this.rdJobUnitName = rdJobUnitName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_BUILDING_ID
	 * @return  the value of TB_READINGDATA.RD_BUILDING_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdBuildingId() {
		return rdBuildingId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_BUILDING_ID
	 * @param rdBuildingId  the value for TB_READINGDATA.RD_BUILDING_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdBuildingId(String rdBuildingId) {
		this.rdBuildingId = rdBuildingId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_BUILDING_NAME
	 * @return  the value of TB_READINGDATA.RD_BUILDING_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdBuildingName() {
		return rdBuildingName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_BUILDING_NAME
	 * @param rdBuildingName  the value for TB_READINGDATA.RD_BUILDING_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdBuildingName(String rdBuildingName) {
		this.rdBuildingName = rdBuildingName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_GROUP_ID
	 * @return  the value of TB_READINGDATA.RD_GROUP_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdGroupId() {
		return rdGroupId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_GROUP_ID
	 * @param rdGroupId  the value for TB_READINGDATA.RD_GROUP_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdGroupId(String rdGroupId) {
		this.rdGroupId = rdGroupId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_GROUP_NAME
	 * @return  the value of TB_READINGDATA.RD_GROUP_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdGroupName() {
		return rdGroupName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_GROUP_NAME
	 * @param rdGroupName  the value for TB_READINGDATA.RD_GROUP_NAME
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdGroupName(String rdGroupName) {
		this.rdGroupName = rdGroupName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_METER_LISTNUMBER
	 * @return  the value of TB_READINGDATA.RD_METER_LISTNUMBER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdMeterListnumber() {
		return rdMeterListnumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_METER_LISTNUMBER
	 * @param rdMeterListnumber  the value for TB_READINGDATA.RD_METER_LISTNUMBER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMeterListnumber(String rdMeterListnumber) {
		this.rdMeterListnumber = rdMeterListnumber;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_METER_LIST_ID
	 * @return  the value of TB_READINGDATA.RD_METER_LIST_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdMeterListId() {
		return rdMeterListId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_METER_LIST_ID
	 * @param rdMeterListId  the value for TB_READINGDATA.RD_METER_LIST_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMeterListId(String rdMeterListId) {
		this.rdMeterListId = rdMeterListId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_METER_PARENT_ID
	 * @return  the value of TB_READINGDATA.RD_METER_PARENT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public String getRdMeterParentId() {
		return rdMeterParentId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_METER_PARENT_ID
	 * @param rdMeterParentId  the value for TB_READINGDATA.RD_METER_PARENT_ID
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdMeterParentId(String rdMeterParentId) {
		this.rdMeterParentId = rdMeterParentId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_USER_READING
	 * @return  the value of TB_READINGDATA.RD_USER_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public Long getRdUserReading() {
		return rdUserReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_USER_READING
	 * @param rdUserReading  the value for TB_READINGDATA.RD_USER_READING
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdUserReading(Long rdUserReading) {
		this.rdUserReading = rdUserReading;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_READINGDATA.RD_USER_USED_WATER
	 * @return  the value of TB_READINGDATA.RD_USER_USED_WATER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public BigDecimal getRdUserUsedWater() {
		return rdUserUsedWater;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_READINGDATA.RD_USER_USED_WATER
	 * @param rdUserUsedWater  the value for TB_READINGDATA.RD_USER_USED_WATER
	 * @mbggenerated  Sat Jun 04 11:58:15 CST 2016
	 */
	public void setRdUserUsedWater(BigDecimal rdUserUsedWater) {
		this.rdUserUsedWater = rdUserUsedWater;
	}
	/**serialVersionUID */
	private static final long serialVersionUID = -6777341761525524976L;
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Readingdata [rdId=");
		builder.append(rdId);
		builder.append(", rdMeterId=");
		builder.append(rdMeterId);
		builder.append(", rdReading=");
		builder.append(rdReading);
		builder.append(", rdTime=");
		builder.append(rdTime);
		builder.append(", rdUnReadType=");
		builder.append(rdUnReadType);
		builder.append(", rdRfidstatus=");
		builder.append(rdRfidstatus);
		builder.append(", rdWaringstatus=");
		builder.append(rdWaringstatus);
		builder.append(", rdPersonId=");
		builder.append(rdPersonId);
		builder.append(", rdPersonName=");
		builder.append(rdPersonName);
		builder.append(", rdTerminalId=");
		builder.append(rdTerminalId);
		builder.append(", rdDatastyle=");
		builder.append(rdDatastyle);
		builder.append(", rdCheckjobId=");
		builder.append(rdCheckjobId);
		builder.append(", rdJobId=");
		builder.append(rdJobId);
		builder.append(", rdAuditStatus=");
		builder.append(rdAuditStatus);
		builder.append(", rdAuditTimeFirst=");
		builder.append(rdAuditTimeFirst);
		builder.append(", rdAuditUidFirst=");
		builder.append(rdAuditUidFirst);
		builder.append(", rdAuditUnameFirst=");
		builder.append(rdAuditUnameFirst);
		builder.append(", rdAuditTimeLast=");
		builder.append(rdAuditTimeLast);
		builder.append(", rdAuditUidLast=");
		builder.append(rdAuditUidLast);
		builder.append(", rdAuditUnameLast=");
		builder.append(rdAuditUnameLast);
		builder.append(", rdImagename=");
		builder.append(rdImagename);
		builder.append(", rdUptime=");
		builder.append(rdUptime);
		builder.append(", rdParentId=");
		builder.append(rdParentId);
		builder.append(", rdReReading=");
		builder.append(rdReReading);
		builder.append(", rdRePersonId=");
		builder.append(rdRePersonId);
		builder.append(", rdReTime=");
		builder.append(rdReTime);
		builder.append(", rdEstimateType=");
		builder.append(rdEstimateType);
		builder.append(", rdEstimateReading=");
		builder.append(rdEstimateReading);
		builder.append(", rdEstimateUserId=");
		builder.append(rdEstimateUserId);
		builder.append(", rdEstimateTime=");
		builder.append(rdEstimateTime);
		builder.append(", rdInvalid=");
		builder.append(rdInvalid);
		builder.append(", rdLoop=");
		builder.append(rdLoop);
		builder.append(", rdUploadUuid=");
		builder.append(rdUploadUuid);
		builder.append(", rdMemo=");
		builder.append(rdMemo);
		builder.append(", rdReadingReal=");
		builder.append(rdReadingReal);
		builder.append(", rdAuditReading=");
		builder.append(rdAuditReading);
		builder.append("]");
		return builder.toString();
	}
	
	
}